src/Entity/Topic.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TopicRepository")
 */
class Topic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="topics")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $timestamp;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Link", mappedBy="topic", orphanRemoval=true)
     */
    private $links;

    public function __construct()
    {
        $this->timestamp = new \DateTime();
        $this->links = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTimestamp(): ?\DateTimeInterface
    {
        return $this->timestamp;
    }

    public function setTimestamp(\DateTimeInterface $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    /**
     * @return Collection|Link[]
     */
    public function getLinks(): Collection
    {
        return $this->links;
    }

    public function addLink(Link $link): self
    {
        if (!$this->links->contains($link)) {
            $this->links[] = $link;
            $link->setTopic($this);
        }

        return $this;
    }

    public function removeLink(Link $link): self
    {
        if ($this->links->contains($link)) {
            $this->links->removeElement($link);
            // set the owning side to null (unless already changed)
            if ($link->getTopic() === $this) {
                $link->setTopic(null);
            }
        }

        return $this;
    }

    public function getSourceCount()
    {
        return count($this->getLinks());
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Topic", mappedBy="user")
     */
    private $topics;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Link", mappedBy="user")
     */
    private $links;

    public function __construct()
    {
        $this->topics = new ArrayCollection();
        $this->links = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Topic[]
     */
    public function getTopics(): Collection
    {
        return $this->topics;
    }

    public function addTopic(Topic $topic): self
    {
        if (!$this->topics->contains($topic)) {
            $this->topics[] = $topic;
            $topic->setUser($this);
        }

        return $this;
    }

    public function removeTopic(Topic $topic): self
    {
        if ($this->topics->contains($topic)) {
            $this->topics->removeElement($topic);
            // set the owning side to null (unless already changed)
            if ($topic->getUser() === $this) {
                $topic->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Link[]
     */
    public function getLinks(): Collection
    {
        return $this->links;
    }

    public function addLink(Link $link): self
    {
        if (!$this->links->contains($link)) {
            $this->links[] = $link;
            $link->setUser($this);
        }

        return $this;
    }

    public function removeLink(Link $link): self
    {
        if ($this->links->contains($link)) {
            $this->links->removeElement($link);
            // set the owning side to null (unless already changed)
            if ($link->getUser() === $this) {
                $link->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Repository\TopicRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    public function __construct(TopicRepository $topics)
    {
        $this->topics = $topics;
    }

    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $topics = $this->topics->findBy([], ['timestamp' => 'ASC']);
        $popularTopics = $this->topics->getTopicsFromLastWeek();
        usort($popularTopics, function ($a, $b)
        {
            return $a->getSourceCount() < $b->getSourceCount();
        });

        return $this->render('default/index.html.twig', [
            'topics' => $topics,
            'popularTopics' => $popularTopics
        ]);
    }

    /**
     * @Route("/single", name="single")
     */
    public function single()
    {
        return $this->render('default/single-view.html.twig');
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Source Exchange
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/index.css">
{% endblock %}

{% block body %}
    <div
        id="feeds" class="container mt-4">
        {# <div id="feed-wrapper"></div> #}
        <div class="card-deck">
            <div id="new" class="card">
                <h3 class="card-header text-white bg-primary">
                    Neueste Themen
                </h3>
                <div class="card-body">
                    <ul class="list-group">
                        {% for topic in topics %}
                            <li class="list-group-item">
                                <a href="{{ path('topic_show', {'id': topic.id}) }}">
                                    <h4 class="topic-main-view">{{ topic.title }}</h4>
                                </a>
                                <h6 class="text-muted description-main-view">{{ topic.description }}</h6>
                                <h6 class="text-muted text-right">{{ topic.sourceCount }}
                                    {% if topic.sourceCount == 1 %}
                                    Quelle
                                    {% else %}
                                    Quellen
                                    {% endif %}
                                </h6>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div id="popular" class="card" border-color="#0E0F0E">
                <h3 class="card-header text-white bg-primary">
                    Populäre Themen
                </h3>
                <div class="card-body">
                    <ul class="list-group">
                        {% for topic in popularTopics %}
                            <li class="list-group-item">
                                <a href="{{ path('topic_show', {'id': topic.id}) }}">
                                    <h4 class="topic-main-view">{{ topic.title }}</h4>
                                </a>
                                <h6 class="text-muted description-main-view">{{ topic.description }}</h6>
                                <h6 class="text-muted text-right">{{ topic.sourceCount }}
                                    {% if topic.sourceCount == 1 %}
                                    Quelle
                                    {% else %}
                                    Quellen
                                    {% endif %}
                                </h6>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/default/mytopics.html.twig
{% extends 'base.html.twig' %}

{% block title %}Source Exchange{% endblock %}

{% block body %}
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Source Exchange</h5>
        <a class="btn btn-outline-primary" href="#">Anmelden</a>
</div>

<div id="feeds" class="container-fluid">
    <div class="row justify-content-center">
    <div class="col-5">
    <div class="card-deck">
    <div id="latest" class="card">
        <div class="card-header">
            Eigene Topics
        </div>
        <div class="card-body">
            <ul class="list-group">
                <li class="list-group-item active">Cras justo odio</li>
                <li class="list-group-item">Dapibus ac facilisis in</li>
                <li class="list-group-item">Morbi leo risus</li>
                <li class="list-group-item">Porta ac consectetur ac</li>
                <li class="list-group-item">Vestibulum at eros</li>
            </ul>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% endblock %}

templates/default/single-view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Source Exchange
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mb-3">
            <div class="col-12">
                <h1 id="topic" class="text-center">
                    {{ topic.title }}
                </h1>
                <div class="col-12 text-muted text-center">
                    {{ topic.description }}
                </div>
            </div>
        </div>
        <div class="row mt-2 justify-content-center">
            <div class="col-12 col-md-6">
                <div id="links" class="card">
                    <div class="card-header">
                        Links zum Thema
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            {% for link in topic.links %}
                                <li class="list-group-item">
                                    <img src={{"https://www.google.com/s2/favicons?domain=" ~ link.href }} class="float-right">
                                    <a class="source-link" href="{{ link.href }}" target="_blank">
                                        {{ link.href }}
                                    </a>
                                    <p class="text-muted"> {{ link.description }} </p>
                                    {% if topicUserMap[link.user.id] is defined %}
                                        <p class="text-muted">Von {{ topicUserMap[link.user.id].username }}</p>
                                    {% endif %}
                                    <button type="button" class="btn btn-outline-danger report-button float-right">Melden</button>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            {% if is_granted('ROLE_USER') %}
            <div class="col-12 col-md-6">
                <div id="links" class="card">
                    <div class="card-header">
                        Neuer Link
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            {{ form(linkForm) }}
                        </ul>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}